FROM golang:1.16 as base

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /opt/app/api

COPY . .

RUN go mod download
RUN go mod verify
RUN go build -o managerapi


CMD ["./managerapi"]
